import { Inter } from 'next/font/google';
import React from 'react';

import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import RootProviders from '@/components/RootProviders';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProviders>
          <Navbar />
          {children}
          <Footer />
        </RootProviders>
      </body>
    </html>
  );
}
